# Use postgres/postgres user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bento

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  bento:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/bento
