version: '3.1'

services:

  db:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  bento:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/bento"
      RUST_LOG: info
