version: '3.1'

services:

  db:
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /mnt/volume_nyc1_02/data:/var/lib/postgresql/data/pgdata


  bento:
    build: .
    restart: no
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432/bento"
      RUST_LOG: info
