x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: 5
      max-size: 20m

services:
  db:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "${PGDATA_MOUNT_PATH}:/var/lib/postgresql/data/pgdata"
      - "./db/init:/docker-entrypoint-initdb.d"
    <<: *logging

  builder:
    build:
      context: .
      dockerfile: builder.dockerfile
    image: builder

  indexer:
    build:
      context: .
      dockerfile: indexer.dockerfile
      args:
        BUILDER_IMAGE: builder
    image: indexer
    restart: always
    depends_on:
      - builder
      - db
    <<: *logging

  api:
    build:
      context: .
      dockerfile: api.dockerfile
      args:
        BUILDER_IMAGE: builder
    restart: always
    depends_on:
      - db
      - builder
    ports:
      - "${API_PORT}:${API_PORT}"
    <<: *logging
