# Use postgres/postgres user/password credentials
version: '3.1'

services:

  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  bento:
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/bento